### ISSUE TITLE
it's not working for me

### ISSUE THREAD

**Issue by MrMayo101** [lncndev/yuki#1]
Hi, i was interested in this work you made so i tried it, the only thing that works for me is the "--help", and to do that, i need to use "sudo yuki --help". but if i do "sudo yuki -t <whatever i type>" it will always output this (below)

Unhandled exception: Error while changing directory: '/home/root/.yuki': No such file or directory (File::NotFoundError)
  from /usr/lib/crystal/crystal/system/unix/dir.cr:52:7 in 'current='
  from /usr/lib/crystal/dir.cr:147:5 in 'cd'
  from /usr/lib/crystal/dir.cr:156:7 in '->'
  from /usr/lib/crystal/primitives.cr:266:3 in 'run'
  from /home/lncn/yuki/src/yuki.cr:8:5 in 'start_parse'
  from /home/lncn/yuki/src/yuki.cr:8:5 in 'start'
  from /home/lncn/yuki/src/yuki.cr:109:1 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:96:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???

do you perhaps know what caused this and how to fix it?

**Comment by ao-social** [comment]
Try running without sudo permissions
